version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: cubeearth/tools-vboxmanage
    volumes:
    - ${DATA_DIR}:/data
